version: '3.9'
services:
  redis:
    image: redis:7.2.3
    hostname: redis
    command: redis-server --save 20 1
    volumes:
      - ./redis-data:/data
    restart: unless-stopped
  app:
    image: jamzdeveloper/change-money:1.1
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    restart: unless-stopped