version: '3'
services:
  redis:
    image: redis:7.2.3
    hostname: redis
  app:
    image: jamzdeveloper/change-money:1.0
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis